### ISSUE TITLE
Can't install EASSE!

### ISSUE THREAD

**Issue by nalfear** [feralvam/easse#105]
I tried EASSE before and it was working with me. Now I am trying to run it and getting errors, is there any problem with it?

ERROR: Failed building wheel for tokenizers
Successfully built tseval
Failed to build tokenizers
ERROR: Could not build wheels for tokenizers which use PEP 517 and cannot be installed directly

**Comment by louismartin** [comment]
Hi @nalfear , sorry for the delay!
How did you solve this in the end?
It might be helpful for others.
