### ISSUE TITLE
Adding Quality Estimation to easse

### ISSUE THREAD

**Issue by louismartin** [feralvam/easse#4]
Hi,

I am working in adding the QE features to easse, I have two questions:

1. I have a bunch of features that can be computed either on the prediction (i.e. length, complexity, lm proba ...) or on both the source and prediction (compression ratio, word embeddings comparison). They can all be found here: https://github.com/facebookresearch/text-simplification-evaluation/blob/master/tseval/feature_extraction.py
What do we want to do with those? Is there a subset of interesting features that we want to include in the evaluate script?

2. Two options on how to integrate them:
   a. Install and import tseval as an external package (most straightforward)
   b. Integrate tseval features to easse (might not be very useful)
  I would suggest choosing a.

**Comment by louismartin** [comment]
Features that might be interesting to see (corpus-level):
- compression ratio
- Number of sentence splits
- Levenshtein distance (character-level and/or word-level)
- Number of exact matches (source not modified)
- Proportion of added words
- Proportion of deleted words
- Average lexical complexity scores ?
- FKGL
- Perplexity of a language model

**Comment by feralvam** [comment]
I also agree with choosing option a. It's better to keep them separated for maintenance reasons, I think. 

I like the features you suggest at the corpus-level.

**Comment by louismartin** [comment]
Ok thanks, I will do that then.
