### ISSUE TITLE
Not loading original sentences for samsa with turk test set

### ISSUE THREAD

**Issue by louismartin** [feralvam/easse#5]
Hi,

Shouldn't we load the original sentences with samsa as well on turk set?

https://github.com/feralvam/easse/blob/44744da64866fac6d6fbef30762fa9ed85c727f1/easse/cli/cli.py#L52

**Comment by feralvam** [comment]
That is correct. I think you already addressed this on your PR?

**Comment by louismartin** [comment]
Yes indeed, closing because it is fixed in #6
