### ISSUE TITLE
Not Found for url: https://pypi.org/simple/tseval/

### ISSUE THREAD

**Issue by yzgdjqwh** [feralvam/easse#51]
WHEN I  "pip install ."

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/tseval/

Why?  Thanks.

**Comment by louismartin** [comment]
Hello,
It seems that pip tries to install tseval from pypi, but that should not happen.
Did you run the `pip install .` command from the same directory as `easse/setup.py` ?

Can you please give use your OS, python, pip and packages versions ?
You can get them with `python --version` and `pip --version` and `pip freeze`

**Comment by yzgdjqwh** [comment]
Python 3.6.9
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

 pip freeze
absl-py==0.9.0
apturl==0.5.2
asn1crypto==0.24.0
astor==0.8.1
attrs==19.3.0
backcall==0.1.0
bayesian-optimization==1.1.0
bleach==3.1.1
blis==0.4.1
boto==2.49.0
boto3==1.12.13
botocore==1.15.13
Brlapi==0.6.6
catalogue==1.0.0
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
Click==7.0
cma==2.7.0
command-not-found==0.3
ConfigArgParse==1.1
cryptography==2.1.4
cupshelpers==1.0
cycler==0.10.0
cymem==2.0.3
Cython==0.29.15
dataclasses==0.7
decorator==4.4.2
defer==1.0.6
defusedxml==0.6.0
dill==0.3.0
distro-info===0.18ubuntu0.18.04.1
docopt==0.6.2
docutils==0.15.2
-e git+https://github.com/facebookresearch/DrQA.git@96f343cac38346d451f6d144a1dfc9d7b4de3db0#egg=drqa
dyNET==2.1
editdistance==0.5.3
elasticsearch==7.5.1
entrypoints==0.3
fairseq==0.9.0
filelock==3.0.12
fire==0.1.3
fuzzywuzzy==0.17.0
gast==0.3.3
gensim==3.8.1
gitdb==4.0.2
gitdb2==4.0.2
GitPython==3.0.2
google-pasta==0.1.8
grpcio==1.27.2
h5py==2.10.0
httplib2==0.9.2
idna==2.9
imohash==1.0.4
importlib-metadata==1.5.0
ipykernel==5.1.4
ipython==7.13.0
ipython-genutils==0.2.0
jedi==0.16.0
Jinja2==2.11.1
jmespath==0.9.5
joblib==0.14.1
json5==0.9.2
jsonschema==3.2.0
jupyter-client==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.3
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterlab==2.0.1
jupyterlab-server==1.0.7
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.1.0
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
Logbook==1.5.3
louis==3.5.0
lxml==4.5.0
macaroonbakery==1.1.3
Mako==1.0.7
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.2.0
mistune==0.8.4
mmh3==2.5.1
murmurhash==1.0.2
nbconvert==5.6.1
nbformat==5.0.4
netifaces==0.10.4
nevergrad==0.2.3
nltk==3.4.5
notebook==6.0.3
numpy==1.18.1
oauth==1.0.1
olefile==0.45.1
pandas==1.0.1
pandocfilters==1.4.2
parsimonious==0.8.1
parso==0.6.2
patsy==0.5.1
Penman==0.6.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
plac==1.1.3
plotly==4.5.4
portalocker==1.5.2
preshed==3.0.2
prettytable==0.7.2
prometheus-client==0.7.1
prompt-toolkit==3.0.4
protobuf==3.11.3
psutil==5.7.0
ptyprocess==0.6.0
pycairo==1.16.2
pycparser==2.20
pycrypto==2.6.1
pycups==1.9.73
Pygments==2.6.1
pygobject==3.26.1
pymacaroons==0.13.0
PyNaCl==1.1.2
pyparsing==2.4.6
pyRFC3339==1.0
pyrsistent==0.15.7
pyspotlight==0.7.2
python-apt==1.6.5+ubuntu0.2
python-dateutil==2.8.1
python-debian==0.1.32
python-Levenshtein==0.12.0
pytorch-bert==1.0.0a4
pytorch-pretrained-bert==0.6.2
pytorch-transformers==1.2.0
pytz==2019.3
pyxdg==0.25
PyYAML==5.3
pyzmq==19.0.0
randaugment==1.0.2
redis==3.2.1
regex==2020.2.20
reportlab==3.4.0
requests==2.23.0
requests-unixsocket==0.1.5
retrying==1.3.3
s3transfer==0.3.3
sacrebleu==1.4.4
sacremoses==0.0.38
scikit-learn==0.22.1
scipy==1.4.1
screen-resolution-extra==0.0.0
SecretStorage==2.3.1
SEMSTR==1.2.2
Send2Trash==1.5.0
sentencepiece==0.1.83
simplejson==3.13.2
six==1.14.0
smart-open==1.9.0
smatch==1.0.1
smmap==3.0.1
spacy==2.2.3
srsly==1.0.1
stanfordcorenlp==3.9.1.1
stanfordnlp==0.2.0
statsmodels==0.11.1
system-service==0.3
systemd-python==234
tabulate==0.8.4
tensorboard==1.14.0
tensorboardX==2.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
tensorflow-hub==0.7.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
thinc==7.3.1
tokenizers==0.5.0
torch==1.4.0
torchvision==0.5.0
tornado==6.0.4
tqdm==4.43.0
traitlets==4.3.3
transformers==2.5.0
ts-eval==0.2.2
TUPA==1.4.2
typing==3.7.4.1
typing-extensions==3.7.4.1
ubuntu-drivers-common==0.0.0
UCCA==1.2.3
ufw==0.36
ujson==1.35
unattended-upgrades==0.1
urllib3==1.25.8
usb-creator==0.3.3
varint==1.0.2
wadllib==1.3.2
wasabi==0.6.0
wcwidth==0.1.8
webencodings==0.5.1
Werkzeug==1.0.0
word2number==1.1
wrapt==1.12.0
xarray==0.15.0
xkit==0.0.0
yattag==1.13.2
zipp==3.1.0
zope.interface==4.3.2

**Comment by louismartin** [comment]
It seems that pip is outdated, can you please upgrade to the latest version and try to install the easse package again ?
`pip install --upgrade pip`

**Comment by yzgdjqwh** [comment]
Thank you very much
