### ISSUE TITLE
easse: command not found

### ISSUE THREAD

**Issue by yzgdjqwh** [feralvam/easse#52]
File "/home/***/easse/**quality_estimation.py**", line 3, in <module>
    from tseval.feature_extraction import (get_compression_ratio, count_sentence_splits, ......
ModuleNotFoundError: No module named **'tseval'**

 EASSE has been installed successfully, but when I run the command-line interface with the easse command.
easse: command not found

**Comment by louismartin** [comment]
That is very likely related to https://github.com/feralvam/easse/issues/51, let's fix the other one first
