### ISSUE TITLE
EASSE does not work with latest version of scarebleu

### ISSUE THREAD

**Issue by louismartin** [feralvam/easse#60]
From https://github.com/facebookresearch/access/issues/10

```
File "/usr/local/lib/python3.6/dist-packages/easse/cli.py", line 130, in evaluate_system_output
lowercase=lowercase)
File "/usr/local/lib/python3.6/dist-packages/easse/bleu.py", line 22, in corpus_bleu
sys_sents = [utils_prep.normalize(sent, lowercase, tokenizer) for sent in sys_sents]
File "/usr/local/lib/python3.6/dist-packages/easse/bleu.py", line 22, in
sys_sents = [utils_prep.normalize(sent, lowercase, tokenizer) for sent in sys_sents]
File "/usr/local/lib/python3.6/dist-packages/easse/utils/preprocessing.py", line 12, in normalize
normalized_sent = sacrebleu.tokenize_13a(sentence)
AttributeError: module 'sacrebleu' has no attribute 'tokenize_13a'
```

**Comment by ztcintokyo** [comment]
Hello, I also got stuck on this problem.
My sacrebleu version is 1.4.14.
Thank you in advance

**Comment by louismartin** [comment]
This bug should be fixed in the latest version of EASSE, can you please update EASSE to the latest version and try again?

**Comment by ztcintokyo** [comment]
I‘m using 0.2.3, not the lastest version?

**Comment by louismartin** [comment]
Yes it is but your error message does not match the code:

`AttributeError: module 'sacrebleu' has no attribute 'tokenize_13a'`, but in the code we never try to access `sacrebleu.tokenize_13a`. We only did this in previous versions.

Maybe you are running in a python runtime (e.g. jupyter or ipython) that has loaded the previous version. Can you please start your python environment again? If it does not work can you uninstall easse and reinstall?
I just pushed some unrelated fixes on master, maybe you can update with this new version as well (version 0.2.4).

**Comment by ztcintokyo** [comment]
OH, I see it.
Thank you for your patience.

**Comment by louismartin** [comment]
Great, closing the issue, feel free to reopen if you have more trouble.
