### ISSUE TITLE
<Issue solved > AssertionError: Please make sure to use IPA dictionary for MeCab

### ISSUE THREAD

**Issue by ykkhan** [feralvam/easse#69]
When I run "pip install ." 
it results in this error. I have python version 3.8
![Screenshot from 2020-08-18 20-09-03](https://user-images.githubusercontent.com/42977303/90530915-dd24bf00-e18e-11ea-9914-b96a3afc4002.png)

**Comment by ykkhan** [comment]
I solved above problem but now I am facing new error
![Screenshot from 2020-08-17 14-11-39](https://user-images.githubusercontent.com/42977303/90379672-74591c00-e094-11ea-8b3f-b246fd74914a.png)

kindly help me to solve this error... I tried

**Comment by feralvam** [comment]
Hello @ykkhan,

Thanks for your interest in EASSE. I believe it's the same problem as in here: https://github.com/feralvam/easse/issues/64#issuecomment-658526299. Could you check if their solution works for you too?

**Comment by ykkhan** [comment]
I solved this issue by downgrade the version of mecab-python3==0.9965 
Now it work fine. 
I successfully installed EASSE. 

May I know, How to apply EASSE on other dataset (Like Simple Wikipedia and Wikipedia simplification corpus).  
I would be great.

**Comment by feralvam** [comment]
Glad to hear you managed to solve your issue! If you want to use the functionalities from inside python, you can follow the example in the README. If you want to use it on the command line, you can specify the paths for the original sentences, system outputs and references as in here:

```
easse evaluate -m "bleu,sari,fkgl" -q -t custom \
--orig_sents_path easse/resources/data/test_sets/turk/test.8turkers.tok.norm \
--refs_sents_paths easse/resources/data/test_sets/turk/test.8turkers.tok.turk.0,easse/resources/data/test_sets/turk/test.8turkers.tok.turk.1,easse/resources/data/test_sets/turk/test.8turkers.tok.turk.2,easse/resources/data/test_sets/turk/test.8turkers.tok.turk.3,easse/resources/data/test_sets/turk/test.8turkers.tok.turk.4,easse/resources/data/test_sets/turk/test.8turkers.tok.turk.5,easse/resources/data/test_sets/turk/test.8turkers.tok.turk.6,easse/resources/data/test_sets/turk/test.8turkers.tok.turk.7 \
--sys_sents_path easse/resources/data/system_outputs/turk/lower/DMASS-DCSS.tok.low
```

**Comment by ykkhan** [comment]
I run it successfully.. Thank you so much..  I am so glad that I reached this point..
![Screenshot from 2020-08-20 19-57-10](https://user-images.githubusercontent.com/42977303/90788789-94504000-e31f-11ea-80a9-89a9fe4e9018.png)

On the other hand, when I am trying to apply it on other custom datasets (mine), It result in this error. As the files is present in the current directory. 
![Screenshot from 2020-08-20 19-56-30](https://user-images.githubusercontent.com/42977303/90789021-d4172780-e31f-11ea-88e5-7e5dc0d271cc.png)

looking forward to your reply.
