### ISSUE TITLE
Apply EASSE on custom dataset.

### ISSUE THREAD

**Issue by ykkhan** [feralvam/easse#70]
I run it successfully.. Thank you so much..  I am so glad that I reached this point..
![Screenshot from 2020-08-20 19-57-10](https://user-images.githubusercontent.com/42977303/90788789-94504000-e31f-11ea-80a9-89a9fe4e9018.png)

On the other hand, when I am trying to apply it on other custom datasets (mine), It result in this error. As the files is present in the current directory. 
![Screenshot from 2020-08-20 19-56-30](https://user-images.githubusercontent.com/42977303/90789021-d4172780-e31f-11ea-88e5-7e5dc0d271cc.png)

looking forward to your reply.

_Originally posted by @ykkhan in https://github.com/feralvam/easse/issues/69#issuecomment-677719765_

**Comment by feralvam** [comment]
Hi @ykkhan,
The error message says that `fc.low` is not in the path that you specified. Could you double check that you put `fc.low` in the folder `easse/resources/data/system_outputs`?

**Comment by ykkhan** [comment]
I have double checked it many time, this directory has the txt file fc.low
![Screenshot from 2020-08-25 07-41-19](https://user-images.githubusercontent.com/42977303/91116807-a2e38200-e6a6-11ea-8603-eadb7a1f9995.png)

I tried to run it in different possible ways (modifying run commands, changing directory etc), But I could not manage this error.

**Comment by ykkhan** [comment]
Thank you for your help, I run in successfully. 
I was making mistake in file name.  Incomplete file name (without extension ".txt") results in error **"not found file"**

**Comment by feralvam** [comment]
Happy that you managed to solve the problem :)
