### ISSUE TITLE
Can EASSE compute SAMSA score. ? 

### ISSUE THREAD

**Issue by ykkhan** [feralvam/easse#73]
I want to compute SAMSA score of corpus.. Can I use EASSE Technique to find out Perfect SAMSA score to Evaluate corpus?

**Comment by feralvam** [comment]
Hi,

I'm sorry, I'm not sure I understand what you mean by "perfect samsa score". SAMSA is a sentence-level metric, and the average of the scores of all sentences in a corpus is the corpus-level score. From [samsa.py](easse/samsa.py), you can use `sentence_samsa` to compute the score of just one sentence pair, `get_samsa_sentence_scores` to obtain the individual scores for all sentence pairs in a list, or `corpus_samsa` to directly obtain the average of all individual scores. 

I hope this helps!

**Comment by ykkhan** [comment]
Thank you for replying

I want to compute SAMSA score of 100 sentences. How to compute SAMSA score using EASSE. 
Is I am giving right command. ? 
sudo easse evaluate -m "bleu,sari,fkgl,**samsa**" -q -t custom --orig_sents_path easse/resources/data/test_sets/th/source --refs_sents_paths easse/resources/data/test_sets/th/reference --sys_sents_path easse/resources/data/test_sets/th/system

**Comment by feralvam** [comment]
Yes, that will give you the corpus-level score. Just a word of caution: SAMSA is a slow metric to compute because it needs to load the model for the semantic parsing, do the semantic parsing and then do the syntactic parsing. Your 100 sentences should take around 4 minutes.

**Comment by ykkhan** [comment]
Ok thank you so much..

**Comment by ykkhan** [comment]
SAMSA is language dependent Or it can be apply to any language. I want to apply it on Urdu language. 
Any Extra steps will I need to find score SAMSA score on this language.?

**Comment by feralvam** [comment]
Unfortunately, SAMSA is English-only. It could theoretically be possible to use in other languages if there were semantic and syntactic parsers specifics for them. But that's beyond what the original and our implementations can do.

**Comment by ykkhan** [comment]
OK, Thank You so much ..

**Comment by anony297** [comment]
I am getting the following error while trying to import samsa

# We don't install tupa by default because it requires the ucca package which hardcodes the spacy version to the old 2.1.3

ModuleNotFoundError: No module named 'tupa

**Comment by louismartin** [comment]
Hi, thanks for the question.
The error is self-explanatory ;) we don't install tupa by default because of requirement problems.
Please install tupa: https://github.com/danielhers/tupa
