### ISSUE TITLE
sentence_sari issue 

### ISSUE THREAD

**Issue by monkdou0** [feralvam/easse#78]
I can't find the defination of the function sentence_sari()
Has it been deprecated?

**Comment by louismartin** [comment]
Hi,
Thanks for the heads up. Yes the readme refers a method that was deleted. You can just use corpus_sari instead on a single sentence. The only difference between the two was that `use_f1_for_deletion=False` for the `sentence_sari` method to match the original implementation: https://github.com/feralvam/easse/blob/662682f23d7e449d2096ffe0df3d66737e582aac/easse/sari.py#L218.
But using F1 for deletion for corpus SARI but not for "sentence" SARI did not make sense, it was probably just a mismatch in the original implementation.

**Comment by monkdou0** [comment]
Thanks! great work

**Comment by louismartin** [comment]
Thanks, feel free to open a new issue if you have other problems!
