### ISSUE TITLE
installation issue in windows 10

### ISSUE THREAD

**Issue by Avishek2020** [feralvam/easse#80]
Log output
Please guide if possible
---------------------------------

(torchenv) C:\Users\avish>cd easse

(torchenv) C:\Users\avish\easse>pip install .
Processing c:\users\avish\easse
Requirement already satisfied: click in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from easse==0.2.4) (7.1.2)
Requirement already satisfied: matplotlib in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from easse==0.2.4) (3.3.2)
Requirement already satisfied: numpy in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from easse==0.2.4) (1.19.1)
Requirement already satisfied: pandas in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from easse==0.2.4) (1.1.3)
Requirement already satisfied: requests>=2.21.0 in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from easse==0.2.4) (2.24.0)
Requirement already satisfied: sacrebleu>=1.4.13 in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from easse==0.2.4) (1.4.14)
Requirement already satisfied: sacremoses in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from easse==0.2.4) (0.0.43)
Requirement already satisfied: seaborn in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from easse==0.2.4) (0.11.1)
Requirement already satisfied: tqdm>=4.32.2 in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from easse==0.2.4) (4.47.0)
Requirement already satisfied: plotly>=4.0.0 in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from easse==0.2.4) (4.14.1)
Collecting ucca@ git+https://github.com/louismartin/ucca.git
  Cloning https://github.com/louismartin/ucca.git to c:\users\avish\appdata\local\temp\pip-install-18t60lo8\ucca_f7611c81e0a345f6b4173600639dba69
Collecting tseval@ git+https://github.com/facebookresearch/text-simplification-evaluation.git
  Cloning https://github.com/facebookresearch/text-simplification-evaluation.git to c:\users\avish\appdata\local\temp\pip-install-18t60lo8\tseval_b5d2a62677ad4f11a57de91eafd65538
Collecting simalign@ git+https://github.com/cisnlp/simalign.git
  Cloning https://github.com/cisnlp/simalign.git to c:\users\avish\appdata\local\temp\pip-install-18t60lo8\simalign_4653354f4cb6415e9156e63e83d2cc24
Requirement already satisfied: torch in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from simalign@ git+https://github.com/cisnlp/simalign.git->easse==0.2.4) (1.6.0)
Requirement already satisfied: scipy in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from simalign@ git+https://github.com/cisnlp/simalign.git->easse==0.2.4) (1.5.4)
Requirement already satisfied: transformers>=3.1.0 in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from simalign@ git+https://github.com/cisnlp/simalign.git->easse==0.2.4) (4.0.0)
Requirement already satisfied: regex in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from simalign@ git+https://github.com/cisnlp/simalign.git->easse==0.2.4) (2020.10.28)
Requirement already satisfied: scikit_learn in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from simalign@ git+https://github.com/cisnlp/simalign.git->easse==0.2.4) (0.23.2)
Requirement already satisfied: gitpython in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from tseval@ git+https://github.com/facebookresearch/text-simplification-evaluation.git->easse==0.2.4) (3.1.11)
Collecting networkx==2.4
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
Requirement already satisfied: decorator>=4.3.0 in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from networkx==2.4->simalign@ git+https://github.com/cisnlp/simalign.git->easse==0.2.4) (4.4.2)
Collecting nltk==3.4.3
  Using cached nltk-3.4.3.zip (1.4 MB)
Requirement already satisfied: six in c:\users\avish\anaconda3\envs\torchenv\lib\site-packages (from nltk==3.4.3->easse==0.2.4) (1.15.0)
Collecting spacy==2.1.3
  Using cached spacy-2.1.3.tar.gz (27.7 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\avish\anaconda3\envs\torchenv\python.exe' 'c:\users\avish\anaconda3\envs\torchenv\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\avish\AppData\Local\Temp\pip-build-env-v4tl30sz\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0.<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' thinc==7.0.0.dev6
       cwd: None
  Complete output (119 lines):
  Collecting thinc==7.0.0.dev6
    Using cached thinc-7.0.0.dev6-cp38-cp38-win_amd64.whl
  Collecting cymem<2.1.0,>=2.0.2
    Using cached cymem-2.0.5-cp38-cp38-win_amd64.whl (36 kB)
  Collecting murmurhash<1.1.0,>=0.28.0
    Using cached murmurhash-1.0.5-cp38-cp38-win_amd64.whl (21 kB)
  Collecting preshed<2.1.0,>=2.0.1
    Using cached preshed-2.0.1.tar.gz (113 kB)
  Collecting wheel>0.32.0.<0.33.0
    Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Collecting blis<0.3.0,>=0.2.1
    Using cached blis-0.2.4.tar.gz (1.5 MB)
  Collecting numpy>=1.7.0
    Using cached numpy-1.19.4-cp38-cp38-win_amd64.whl (13.0 MB)
  Collecting plac<1.0.0,>=0.9.6
    Using cached plac-0.9.6-py2.py3-none-any.whl (20 kB)
  Collecting six<2.0.0,>=1.10.0
    Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
  Collecting srsly<1.1.0,>=0.0.5
    Using cached srsly-1.0.5-cp38-cp38-win_amd64.whl (178 kB)
  Collecting thinc-gpu-ops<0.1.0,>=0.0.1
    Using cached thinc_gpu_ops-0.0.4-py3-none-any.whl
  Collecting tqdm<5.0.0,>=4.10.0
    Using cached tqdm-4.55.0-py2.py3-none-any.whl (68 kB)
  Collecting wasabi<1.1.0,>=0.0.9
    Using cached wasabi-0.8.0-py3-none-any.whl (23 kB)
  Collecting wrapt<1.11.0,>=1.10.0
    Using cached wrapt-1.10.11-cp38-cp38-win_amd64.whl
  Collecting Cython
    Using cached Cython-0.29.21-cp38-cp38-win_amd64.whl (1.7 MB)
  Collecting setuptools
    Using cached setuptools-51.1.1-py3-none-any.whl (2.0 MB)
  Building wheels for collected packages: preshed, blis
    Building wheel for preshed (setup.py): started
    Building wheel for preshed (setup.py): finished with status 'done'
    Created wheel for preshed: filename=preshed-2.0.1-cp38-cp38m-win_amd64.whl size=79134 sha256=86512a35c98ce3fb730879436319707087bd6a2a7efc386945eb51e38ee60e01
    Stored in directory: c:\users\avish\appdata\local\pip\cache\wheels\5a\d0\29\7f6993a759349eae3d0ecca7e2fbc88acdd8650b25e6c6ad8a
    Building wheel for blis (setup.py): started
    Building wheel for blis (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\avish\anaconda3\envs\torchenv\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\avish\\AppData\\Local\\Temp\\pip-install-o73hzbxv\\blis_26e7809c4855422bbbd89fdb5d389c5c\\setup.py'"'"'; __file__='"'"'C:\\Users\\avish\\AppData\\Local\\Temp\\pip-install-o73hzbxv\\blis_26e7809c4855422bbbd89fdb5d389c5c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\avish\AppData\Local\Temp\pip-wheel-empit83q'
         cwd: C:\Users\avish\AppData\Local\Temp\pip-install-o73hzbxv\blis_26e7809c4855422bbbd89fdb5d389c5c\
    Complete output (31 lines):
    BLIS_COMPILER? None
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\blis
    copying blis\about.py -> build\lib.win-amd64-3.8\blis
    copying blis\benchmark.py -> build\lib.win-amd64-3.8\blis
    copying blis\__init__.py -> build\lib.win-amd64-3.8\blis
    creating build\lib.win-amd64-3.8\blis\tests
    copying blis\tests\common.py -> build\lib.win-amd64-3.8\blis\tests
    copying blis\tests\test_dotv.py -> build\lib.win-amd64-3.8\blis\tests
    copying blis\tests\test_gemm.py -> build\lib.win-amd64-3.8\blis\tests
    copying blis\tests\__init__.py -> build\lib.win-amd64-3.8\blis\tests
    copying blis\cy.pyx -> build\lib.win-amd64-3.8\blis
    copying blis\py.pyx -> build\lib.win-amd64-3.8\blis
    copying blis\cy.pxd -> build\lib.win-amd64-3.8\blis
    copying blis\__init__.pxd -> build\lib.win-amd64-3.8\blis
    running build_ext
    c:\users\avish\anaconda3\envs\torchenv\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\avish\AppData\Local\Temp\pip-install-o73hzbxv\blis_26e7809c4855422bbbd89fdb5d389c5c\blis\cy.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    c:\users\avish\anaconda3\envs\torchenv\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\avish\AppData\Local\Temp\pip-install-o73hzbxv\blis_26e7809c4855422bbbd89fdb5d389c5c\blis\py.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    Processing blis\cy.pyx
    Processing blis\py.pyx
    error: [WinError 2] The system cannot find the file specified
    msvc
    py_compiler msvc
    {'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'HOSTTYPE': 'x86_64', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LANG': 'C.UTF-8', 'OLDPWD': '/home/matt/repos/flame-blis', 'VIRTUAL_ENV': '/home/matt/repos/cython-blis/env3.6', 'USER': 'matt', 'PWD': '/home/matt/repos/cython-blis', 'HOME': '/home/matt', 'NAME': 'LAPTOP-OMKOB3VM', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'SHELL': '/bin/bash', 'TERM': 'xterm-256color', 'SHLVL': '1', 'LOGNAME': 'matt', 'PATH': '/home/matt/repos/cython-blis/env3.6/bin:/tmp/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5/ConEmu/Scripts:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5/ConEmu:/mnt/c/Python37/Scripts:/mnt/c/Python37:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/LLVM/bin:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/nodejs:/mnt/c/Users/matt/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/matt/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/matt/AppData/Roaming/npm:/snap/bin:/mnt/c/Program Files/Oracle/VirtualBox', 'PS1': '(env3.6) \\[\\e]0;\\u@\\h: \\w\\a\\]${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ ', 'VAGRANT_HOME': '/home/matt/.vagrant.d/', 'LESSOPEN': '| /usr/bin/lesspipe %s', '_': '/home/matt/repos/cython-blis/env3.6/bin/python'}
    clang -c C:\Users\avish\AppData\Local\Temp\pip-install-o73hzbxv\blis_26e7809c4855422bbbd89fdb5d389c5c\blis\_src\config\bulldozer\bli_cntx_init_bulldozer.c -o C:\Users\avish\AppData\Local\Temp\tmp417dls1b\bli_cntx_init_bulldozer.o -O2 -funroll-all-loops -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude\windows-x86_64 -I.\frame\3\ -I.\frame\ind\ukernels\ -I.\frame\1m\ -I.\frame\1f\ -I.\frame\1\ -I.\frame\include -IC:\Users\avish\AppData\Local\Temp\pip-install-o73hzbxv\blis_26e7809c4855422bbbd89fdb5d389c5c\blis\_src\include\windows-x86_64
    ----------------------------------------
    ERROR: Failed building wheel for blis
    Running setup.py clean for blis
  Successfully built preshed
  Failed to build blis
  Installing collected packages: numpy, cymem, wrapt, wasabi, tqdm, thinc-gpu-ops, srsly, six, preshed, plac, murmurhash, blis, wheel, thinc, setuptools, Cython
      Running setup.py install for blis: started
      Running setup.py install for blis: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\avish\anaconda3\envs\torchenv\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\avish\\AppData\\Local\\Temp\\pip-install-o73hzbxv\\blis_26e7809c4855422bbbd89fdb5d389c5c\\setup.py'"'"'; __file__='"'"'C:\\Users\\avish\\AppData\\Local\\Temp\\pip-install-o73hzbxv\\blis_26e7809c4855422bbbd89fdb5d389c5c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\avish\AppData\Local\Temp\pip-record-jbidoyjp\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\avish\AppData\Local\Temp\pip-build-env-v4tl30sz\overlay' --compile --install-headers 'C:\Users\avish\AppData\Local\Temp\pip-build-env-v4tl30sz\overlay\Include\blis'
           cwd: C:\Users\avish\AppData\Local\Temp\pip-install-o73hzbxv\blis_26e7809c4855422bbbd89fdb5d389c5c\
      Complete output (31 lines):
      BLIS_COMPILER? None
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\blis
      copying blis\about.py -> build\lib.win-amd64-3.8\blis
      copying blis\benchmark.py -> build\lib.win-amd64-3.8\blis
      copying blis\__init__.py -> build\lib.win-amd64-3.8\blis
      creating build\lib.win-amd64-3.8\blis\tests
      copying blis\tests\common.py -> build\lib.win-amd64-3.8\blis\tests
      copying blis\tests\test_dotv.py -> build\lib.win-amd64-3.8\blis\tests
      copying blis\tests\test_gemm.py -> build\lib.win-amd64-3.8\blis\tests
      copying blis\tests\__init__.py -> build\lib.win-amd64-3.8\blis\tests
      copying blis\cy.pyx -> build\lib.win-amd64-3.8\blis
      copying blis\py.pyx -> build\lib.win-amd64-3.8\blis
      copying blis\cy.pxd -> build\lib.win-amd64-3.8\blis
      copying blis\__init__.pxd -> build\lib.win-amd64-3.8\blis
      running build_ext
      c:\users\avish\anaconda3\envs\torchenv\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\avish\AppData\Local\Temp\pip-install-o73hzbxv\blis_26e7809c4855422bbbd89fdb5d389c5c\blis\cy.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      c:\users\avish\anaconda3\envs\torchenv\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\avish\AppData\Local\Temp\pip-install-o73hzbxv\blis_26e7809c4855422bbbd89fdb5d389c5c\blis\py.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      Processing blis\cy.pyx
      Processing blis\py.pyx
      error: [WinError 2] The system cannot find the file specified
      msvc
      py_compiler msvc
      {'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'HOSTTYPE': 'x86_64', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LANG': 'C.UTF-8', 'OLDPWD': '/home/matt/repos/flame-blis', 'VIRTUAL_ENV': '/home/matt/repos/cython-blis/env3.6', 'USER': 'matt', 'PWD': '/home/matt/repos/cython-blis', 'HOME': '/home/matt', 'NAME': 'LAPTOP-OMKOB3VM', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'SHELL': '/bin/bash', 'TERM': 'xterm-256color', 'SHLVL': '1', 'LOGNAME': 'matt', 'PATH': '/home/matt/repos/cython-blis/env3.6/bin:/tmp/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5/ConEmu/Scripts:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5/ConEmu:/mnt/c/Python37/Scripts:/mnt/c/Python37:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/LLVM/bin:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/nodejs:/mnt/c/Users/matt/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/matt/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/matt/AppData/Roaming/npm:/snap/bin:/mnt/c/Program Files/Oracle/VirtualBox', 'PS1': '(env3.6) \\[\\e]0;\\u@\\h: \\w\\a\\]${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ ', 'VAGRANT_HOME': '/home/matt/.vagrant.d/', 'LESSOPEN': '| /usr/bin/lesspipe %s', '_': '/home/matt/repos/cython-blis/env3.6/bin/python'}
      clang -c C:\Users\avish\AppData\Local\Temp\pip-install-o73hzbxv\blis_26e7809c4855422bbbd89fdb5d389c5c\blis\_src\config\bulldozer\bli_cntx_init_bulldozer.c -o C:\Users\avish\AppData\Local\Temp\tmp2fqmgjbi\bli_cntx_init_bulldozer.o -O2 -funroll-all-loops -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude\windows-x86_64 -I.\frame\3\ -I.\frame\ind\ukernels\ -I.\frame\1m\ -I.\frame\1f\ -I.\frame\1\ -I.\frame\include -IC:\Users\avish\AppData\Local\Temp\pip-install-o73hzbxv\blis_26e7809c4855422bbbd89fdb5d389c5c\blis\_src\include\windows-x86_64
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'c:\users\avish\anaconda3\envs\torchenv\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\avish\\AppData\\Local\\Temp\\pip-install-o73hzbxv\\blis_26e7809c4855422bbbd89fdb5d389c5c\\setup.py'"'"'; __file__='"'"'C:\\Users\\avish\\AppData\\Local\\Temp\\pip-install-o73hzbxv\\blis_26e7809c4855422bbbd89fdb5d389c5c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\avish\AppData\Local\Temp\pip-record-jbidoyjp\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\avish\AppData\Local\Temp\pip-build-env-v4tl30sz\overlay' --compile --install-headers 'C:\Users\avish\AppData\Local\Temp\pip-build-env-v4tl30sz\overlay\Include\blis' Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\avish\anaconda3\envs\torchenv\python.exe' 'c:\users\avish\anaconda3\envs\torchenv\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\avish\AppData\Local\Temp\pip-build-env-v4tl30sz\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0.<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' thinc==7.0.0.dev6 Check the logs for full command output.

(torchenv) C:\Users\avish\easse>_

**Comment by feralvam** [comment]
Hi!
It seems to me that the key error message is here:

`error: [WinError 2] The system cannot find the file specified
msvc
py_compiler msvc`

Does the solution outline [here](https://stackoverflow.com/questions/55298505/spacy-update-msvc-not-found) help?

**Comment by Avishek2020** [comment]
Hi Fernando,
Thanks, it helped me to get clue. I had spacy version 2.2.2.& Python 3.8
![spacy_LI](https://user-images.githubusercontent.com/16956604/103358046-fa5e8800-4ab4-11eb-97be-8bb2fbc77e97.jpg)

So, to resolve it i created a virtual environment with python 3.6.
and install easse. it works now but can you please have a quick look on this error while running my dataset.

https://colab.research.google.com/drive/1iTId7uPlMNMMeSz6QuY1CDFxU6GBv4qY?usp=sharing

**Comment by feralvam** [comment]
Hi!
Note that for both `corpus_sari` and `corpus_bleu` the `refs_sents` argument is `List[List[str]]`.  This is to account for the general case where multiple references are available for each instance. You didn't get an error with `corpus_sari` because we don't make the same verification as sacrebleu (maybe we should), but the sari score you get is most likely incorrect. You should change the way you are calling the functions so that, for each instance, the `refs_sents` argument is a List.

**Comment by Avishek2020** [comment]
OK, so it means i cannot use easse or i need to change it files .[bleu.py, sari.py]
sys_sent: List[str],  ref_sents: List[str],

But my input has will be like it. as i am doing translation
https://colab.research.google.com/drive/1iTId7uPlMNMMeSz6QuY1CDFxU6GBv4qY?usp=sharing

**Comment by feralvam** [comment]
It means that you need to reformat your input so that what you pass in the `refs_sents` argument is a `List[List[str]]`. For example, you could change the way you load your data into the dataframe so that each item in the `Target_Text` column is a list of only one element.

**Comment by Avishek2020** [comment]
ok thank you

**Comment by Avishek2020** [comment]
understand

**Comment by louismartin** [comment]
> Hi!
> Note that for both `corpus_sari` and `corpus_bleu` the `refs_sents` argument is `List[List[str]]`. This is to account for the general case where multiple references are available for each instance. You didn't get an error with `corpus_sari` because we don't make the same verification as sacrebleu (maybe we should), but the sari score you get is most likely incorrect. You should change the way you are calling the functions so that, for each instance, the `refs_sents` argument is a List.

@feralvam can you create a new issue highlighting what we need to do ideally to fix this problem in the future?
