### ISSUE TITLE
result dismatch with paper 

### ISSUE THREAD

**Issue by monkdou0** [feralvam/easse#81]
the result of SARI and bleu to model is mismatch with the original paper 
WHY?????
![image](https://user-images.githubusercontent.com/68677162/104283824-179b4980-54ec-11eb-86fb-fca150cbaacd.png)

![image](https://user-images.githubusercontent.com/68677162/104283849-2124b180-54ec-11eb-81f6-c5c4817cbbef.png)

**Comment by louismartin** [comment]
Hello @monkdou0 
Thanks for the issue.
As mentioned in the [the last section of the README](https://github.com/feralvam/easse#differences-with-original-sari-implementation), the EASSE implementation fixes bugs and inconsistencies with previous versions of SARI that were used in earlier works.
The scores are not the same although similar.
We highly recommend to use this fixed version and recompute scores using the system outputs provided in the library.

**Comment by louismartin** [comment]
If you use the latest version of EASSE, you will get these results:
```
$ easse evaluate -t turkcorpus_test -m sari,bleu -i easse/resources/data/system_outputs/turkcorpus/test/Hybrid
{'bleu': 50.707, 'sari': 31.497}
```

**Comment by monkdou0** [comment]
my version is 580bba7e1378fc8289c663f864e0487188fe8067,
and the result is 
➜ easse evaluate -t turkcorpus_test -m sari,bleu -i easse/resources/data/system_outputs/turkcorpus/test/Hybrid
{'bleu': 50.707, 'sari': 28.154}

**Comment by monkdou0** [comment]
I have find what's wrong with me
THx! @louismartin

**Comment by louismartin** [comment]
Hi @monkdou0 do you mind sharing what was wrong with us?
It might help other people in the future!

**Comment by monkdou0** [comment]
That is totally my own fault.
i change the code of the implementation of SARI function  several days ago, and compile it today.
This repo is useful for the task of text simplification.
Very good! thx

**Comment by louismartin** [comment]
Ok thanks, closing the issue then!
