### ISSUE TITLE
ERROR:  local variable 'NISTTokenizer' referenced before assignment

### ISSUE THREAD

**Issue by nalfear** [feralvam/easse#82]
I am trying to run this command
easse evaluate -t turkcorpus_test -m 'bleu,sari' -q < easse/resources/data/system_outputs/turkcorpus/test/ACCESS
and I got this error
UnboundLocalError: local variable 'NISTTokenizer' referenced before assignment

**Comment by louismartin** [comment]
Hi, thanks for the issue!
I cannot reproduce this on my end with the latest version of EASSE.
Furthermore we don't use NISTTokenizer in EASSE, are you sure it's not related to some code that you wrote?
Can you attach the full error message with the stack trace?
Thanks!

**Comment by nalfear** [comment]
It works now, thank you.
