### ISSUE TITLE
multiple system report error

### ISSUE THREAD

**Issue by monkdou0** [feralvam/easse#83]
when i want to get the report for mulriple system report i get this error,
![image](https://user-images.githubusercontent.com/68677162/107120582-62c93200-68c9-11eb-95fe-44414ee262db.png)

when run  easse report -t asset_test -i  ./ACCESS  -p /Users/man/Desktop/MonkAcademic/academic/monkSS/evaluate/result/report/SBMT-SARI-asset.html
and easse report -t asset_test -i  ./SBMT-SARI  -p /Users/man/Desktop/MonkAcademic/academic/monkSS/evaluate/result/report/SBMT-SARI-asset.html
it is fine
why this error?

**Comment by louismartin** [comment]
Thanks for noticing this bug, I'm working on a fix right now.

**Comment by louismartin** [comment]
I pushed a fix, it should be working fine now.
