### ISSUE TITLE
Failed to compute SAMSA

### ISSUE THREAD

**Issue by valance** [feralvam/easse#88]
Hi all, 

I got this error message when computing SAMSA.

Here is my code:

> from easse.samsa import sentence_samsa
> ori_sent = 'I read the book that John wrote.'
> simp_sent = 'John wrote a book. I read that book.'
> sentence_samsa(orig_sent=ori_sent, sys_sent=simp_sent)

Here is the error message:

> Starting server with command: java -Xmx5G -cp /Applications/anaconda3/envs/OpenNLP/lib/python3.7/site-packages/easse/resources/tools/stanford-corenlp-full-2018-10-05/* edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 60000 -threads 40 -maxCharLength 100000 -quiet True -serverProperties corenlp_server-0b93463ac4344542.props -preload tokenize,ssplit,pos,lemma,ner,depparse
>   File "/Applications/anaconda3/envs/OpenNLP/lib/python3.7/site-packages/stanfordnlp/server/client.py", line 137, in ensure_alive
>    raise PermanentlyFailedException("Timed out waiting for service to come alive.")
> PermanentlyFailedException: Timed out waiting for service to come alive.

<img width="1280" alt="Screen Shot 2021-07-08 at 5 13 15 PM" src="https://user-images.githubusercontent.com/1653088/125008660-8b7e6f00-e095-11eb-9b89-ab1a518f4727.png">

**Comment by louismartin** [comment]
Hi, sorry for the delay.
Do you know if java is correctly installed on your system?
Please try to use this command `java -Xmx5G -cp /Applications/anaconda3/envs/OpenNLP/lib/python3.7/site-packages/easse/resources/tools/stanford-corenlp-full-2018-10-05/* edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 60000 -threads 40 -maxCharLength 100000 -quiet True -serverProperties corenlp_server-0b93463ac4344542.props -preload tokenize,ssplit,pos,lemma,ner,depparse` in a terminal to check what is the exact error.
