### ISSUE TITLE
Referenceless Quality Estimation

### ISSUE THREAD

**Issue by lmvasque** [feralvam/easse#89]
Hi everyone,

I'm interested in using this feature: **Referenceless Quality Estimation** to compare the inputs and the system-generated output.

However, it always asks for the test set. Is this something I can compute with ease? This is my command line:
```bash
easse evaluate --orig_sents_path file1.txt --sys_sents_path file2.txt -m fkgl
```

If so, what features are available in this setting besides FKGL?

Thanks for your support,

Laura

**Comment by louismartin** [comment]
Hi @lmvasque 
Sorry for the delay!
You can access other quality estimation features using `-q`.
However I think that currently the `easse evaluate` command requires a reference path although it's not needed. 
A hack would be to use somthing like `--test_set custom --refs_sents_paths {source_path}` even though the reference will not be used.

**Comment by lmvasque** [comment]
Thanks for the workaround, it is working now :)
```
easse evaluate -q --orig_sents_path test.8turkers.tok.norm --sys_sents_path test.8turkers.tok.simp -m fkgl --test_set custom --refs_sents_paths test.8turkers.tok.norm
{'fkgl': 8.367, 'quality_estimation': {'Compression ratio': 0.926, 'Sentence splits': 1.011, 'Levenshtein similarity': 0.821, 'Exact copies': 0.0, 'Additions proportion': 0.187, 'Deletions proportion': 0.205, 'Lexical complexity score': 8.045}}
```

**Comment by louismartin** [comment]
Ok perfect!
