### ISSUE TITLE
(pip) ERROR: Failed building wheel for easse

### ISSUE THREAD

**Issue by aminthemar** [feralvam/easse#93]
Hello to all you wonderful people,
I've been using your framework for months and I must say, it's great!
However, recently the same package installation command which is `pip install .` has been running into errors and fails to build a wheel for easse.

I share the error message here for more information.
_(It should be noted that this is a standard Google Colab notebook and pip is upgraded to the latest version.)_

> Processing /content/gdrive/My Drive/EASSE/easse
>   Preparing metadata (setup.py) ... done
> .
> .
> .
> Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from python-Levenshtein->tseval@ git+https://github.com/facebookresearch/text-simplification-evaluation.git->easse==0.2.4) (57.4.0)
> Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->simalign@ git+https://github.com/cisnlp/simalign.git->easse==0.2.4) (3.0.0)
> Collecting smmap<6,>=3.0.1
>   Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
> Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->transformers>=3.0.0numpy->bert_score->easse==0.2.4) (3.6.0)
> Building wheels for collected packages: easse, nltk, simalign, tseval, yattag, python-Levenshtein
>   Building wheel for easse (setup.py) ... error
>
>   **ERROR: Failed building wheel for easse**
>
>   Running setup.py clean for easse
>   Building wheel for nltk (setup.py) ... done
>   Created wheel for nltk: filename=nltk-3.4.3-py3-none-any.whl size=1448609 sha256=46052f128d317e2f399f382e992a766ee4e58e8cbe73488125ed811cad6bd10d
>   Stored in directory: /root/.cache/pip/wheels/8f/12/6d/7d1ecf74380e441128c7895cafb1931c746b484237be23a229
>   Building wheel for simalign (pyproject.toml) ... done
>   Created wheel for simalign: filename=simalign-0.3-py3-none-any.whl size=8101 sha256=cefdc8c81226f8c6a1e8a237242dd88aaace6e06a6fa35e8e1adfb343af7cd22
>   Stored in directory: /tmp/pip-ephem-wheel-cache-aypivvq8/wheels/7c/fd/e8/feb79b708710c76e78b833a417552cadc858dd3d2ee5897585
> .
> .
> .
> Failed to build easse
> Installing collected packages: smmap, pyyaml, tokenizers, sacremoses, huggingface-hub, gitdb, transformers, python-Levenshtein, portalocker, nltk, networkx, gitpython, colorama, yattag, tseval, stanfordnlp, simalign, sacrebleu, bert-score, easse
>   Attempting uninstall: pyyaml
>     Found existing installation: PyYAML 3.13
>     Uninstalling PyYAML-3.13:
>       Successfully uninstalled PyYAML-3.13
>   Attempting uninstall: nltk
>     Found existing installation: nltk 3.2.5
>     Uninstalling nltk-3.2.5:
>       Successfully uninstalled nltk-3.2.5
>   Attempting uninstall: networkx
>     Found existing installation: networkx 2.6.3
>     Uninstalling networkx-2.6.3:
>       Successfully uninstalled networkx-2.6.3
>     Running setup.py install for easse ... error
>
> **ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/gdrive/My Drive/EASSE/easse/setup.py'"'"'; __file__='"'"'/content/gdrive/My Drive/EASSE/easse/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qi6q_mqi/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/easse Check the logs for full command output.**

**Comment by feralvam** [comment]
Hi! Thanks for using EASSE and for letting us know of this issue. The easiest solution is to install the package in editable mode, like this:`pip install -e .` Let us know if that works for you or not.

**Comment by aminthemar** [comment]
> 

Yes, that `-e` fixed the error and now it works as always! Thank you for your fast response.
